/* tslint:disable */
/* eslint-disable */
/**
 * Apicurio Registry API [v2]
 * Apicurio Registry is a datastore for standard event schemas and API designs. Apicurio Registry enables developers to manage and share the structure of their data using a REST interface. For example, client applications can dynamically push or pull the latest updates to or from the registry without needing to redeploy. Apicurio Registry also enables developers to create rules that govern how registry content can evolve over time. For example, this includes rules for content validation and version compatibility.  The Apicurio Registry REST API enables client applications to manage the artifacts in the registry. This API provides create, read, update, and delete operations for schema and API artifacts, rules, versions, and metadata.   The supported artifact types include: - Apache Avro schema - AsyncAPI specification - Google protocol buffers - GraphQL schema - JSON Schema - Kafka Connect schema - OpenAPI specification - Web Services Description Language - XML Schema Definition   **Important**: The Apicurio Registry REST API is available from `https://MY-REGISTRY-URL/apis/registry/v2` by default. Therefore you must prefix all API operation paths with `../apis/registry/v2` in this case. For example: `../apis/registry/v2/ids/globalIds/{globalId}`. 
 *
 * The version of the OpenAPI document: 2.2.0.Final
 * Contact: apicurio@lists.jboss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * All error responses, whether `4xx` or `5xx` will include one of these as the response
 * body.
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * The short error message.
     * @type {string}
     * @memberof ModelError
     */
    message?: string;
    /**
     * The server-side error code.
     * @type {number}
     * @memberof ModelError
     */
    errorCode?: number;
    /**
     * Full details about the error.  This might contain a server stack trace, for example.
     * @type {string}
     * @memberof ModelError
     */
    detail?: string;
    /**
     * The error name - typically the classname of the exception thrown by the server.
     * @type {string}
     * @memberof ModelError
     */
    name?: string;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'errorCode': !exists(json, 'error_code') ? undefined : json['error_code'],
        'detail': !exists(json, 'detail') ? undefined : json['detail'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function ModelErrorToJSON(value?: ModelError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'error_code': value.errorCode,
        'detail': value.detail,
        'name': value.name,
    };
}

