/* tslint:disable */
/* eslint-disable */
/**
 * Apicurio Registry API [v2]
 * Apicurio Registry is a datastore for standard event schemas and API designs. Apicurio Registry enables developers to manage and share the structure of their data using a REST interface. For example, client applications can dynamically push or pull the latest updates to or from the registry without needing to redeploy. Apicurio Registry also enables developers to create rules that govern how registry content can evolve over time. For example, this includes rules for content validation and version compatibility.  The Apicurio Registry REST API enables client applications to manage the artifacts in the registry. This API provides create, read, update, and delete operations for schema and API artifacts, rules, versions, and metadata.   The supported artifact types include: - Apache Avro schema - AsyncAPI specification - Google protocol buffers - GraphQL schema - JSON Schema - Kafka Connect schema - OpenAPI specification - Web Services Description Language - XML Schema Definition   **Important**: The Apicurio Registry REST API is available from `https://MY-REGISTRY-URL/apis/registry/v2` by default. Therefore you must prefix all API operation paths with `../apis/registry/v2` in this case. For example: `../apis/registry/v2/ids/globalIds/{globalId}`. 
 *
 * The version of the OpenAPI document: 2.2.0.Final
 * Contact: apicurio@lists.jboss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ArtifactState,
    ArtifactStateFromJSON,
    ArtifactStateFromJSONTyped,
    ArtifactStateToJSON,
} from './ArtifactState';
import {
    ArtifactType,
    ArtifactTypeFromJSON,
    ArtifactTypeFromJSONTyped,
    ArtifactTypeToJSON,
} from './ArtifactType';

/**
 * Models a single artifact from the result set returned when searching for artifacts.
 * @export
 * @interface SearchedVersion
 */
export interface SearchedVersion {
    /**
     * 
     * @type {string}
     * @memberof SearchedVersion
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchedVersion
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof SearchedVersion
     */
    createdOn: Date;
    /**
     * 
     * @type {string}
     * @memberof SearchedVersion
     */
    createdBy: string;
    /**
     * 
     * @type {ArtifactType}
     * @memberof SearchedVersion
     */
    type: ArtifactType;
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchedVersion
     */
    labels?: Array<string>;
    /**
     * 
     * @type {ArtifactState}
     * @memberof SearchedVersion
     */
    state: ArtifactState;
    /**
     * 
     * @type {number}
     * @memberof SearchedVersion
     */
    globalId: number;
    /**
     * 
     * @type {string}
     * @memberof SearchedVersion
     */
    version: string;
    /**
     * User-defined name-value pairs. Name and value must be strings.
     * @type {{ [key: string]: string; }}
     * @memberof SearchedVersion
     */
    properties?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof SearchedVersion
     */
    contentId: number;
}

export function SearchedVersionFromJSON(json: any): SearchedVersion {
    return SearchedVersionFromJSONTyped(json, false);
}

export function SearchedVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchedVersion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'createdOn': (new Date(json['createdOn'])),
        'createdBy': json['createdBy'],
        'type': ArtifactTypeFromJSON(json['type']),
        'labels': !exists(json, 'labels') ? undefined : json['labels'],
        'state': ArtifactStateFromJSON(json['state']),
        'globalId': json['globalId'],
        'version': json['version'],
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
        'contentId': json['contentId'],
    };
}

export function SearchedVersionToJSON(value?: SearchedVersion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'createdOn': (value.createdOn.toISOString()),
        'createdBy': value.createdBy,
        'type': ArtifactTypeToJSON(value.type),
        'labels': value.labels,
        'state': ArtifactStateToJSON(value.state),
        'globalId': value.globalId,
        'version': value.version,
        'properties': value.properties,
        'contentId': value.contentId,
    };
}

