/* tslint:disable */
/* eslint-disable */
/**
 * Apicurio Registry API [v2]
 * Apicurio Registry is a datastore for standard event schemas and API designs. Apicurio Registry enables developers to manage and share the structure of their data using a REST interface. For example, client applications can dynamically push or pull the latest updates to or from the registry without needing to redeploy. Apicurio Registry also enables developers to create rules that govern how registry content can evolve over time. For example, this includes rules for content validation and version compatibility.  The Apicurio Registry REST API enables client applications to manage the artifacts in the registry. This API provides create, read, update, and delete operations for schema and API artifacts, rules, versions, and metadata.   The supported artifact types include: - Apache Avro schema - AsyncAPI specification - Google protocol buffers - GraphQL schema - JSON Schema - Kafka Connect schema - OpenAPI specification - Web Services Description Language - XML Schema Definition   **Important**: The Apicurio Registry REST API is available from `https://MY-REGISTRY-URL/apis/registry/v2` by default. Therefore you must prefix all API operation paths with `../apis/registry/v2` in this case. For example: `../apis/registry/v2/ids/globalIds/{globalId}`. 
 *
 * The version of the OpenAPI document: 2.2.0.Final
 * Contact: apicurio@lists.jboss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ArtifactState,
    ArtifactStateFromJSON,
    ArtifactStateFromJSONTyped,
    ArtifactStateToJSON,
} from './ArtifactState';
import {
    ArtifactType,
    ArtifactTypeFromJSON,
    ArtifactTypeFromJSONTyped,
    ArtifactTypeToJSON,
} from './ArtifactType';

/**
 * Models a single artifact from the result set returned when searching for artifacts.
 * @export
 * @interface SearchedArtifact
 */
export interface SearchedArtifact {
    /**
     * The ID of a single artifact.
     * @type {string}
     * @memberof SearchedArtifact
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SearchedArtifact
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchedArtifact
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchedArtifact
     */
    createdOn: string;
    /**
     * 
     * @type {string}
     * @memberof SearchedArtifact
     */
    createdBy: string;
    /**
     * 
     * @type {ArtifactType}
     * @memberof SearchedArtifact
     */
    type: ArtifactType;
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchedArtifact
     */
    labels?: Array<string>;
    /**
     * 
     * @type {ArtifactState}
     * @memberof SearchedArtifact
     */
    state: ArtifactState;
    /**
     * 
     * @type {string}
     * @memberof SearchedArtifact
     */
    modifiedOn?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchedArtifact
     */
    modifiedBy?: string;
    /**
     * An ID of a single artifact group.
     * @type {string}
     * @memberof SearchedArtifact
     */
    groupId?: string;
}

export function SearchedArtifactFromJSON(json: any): SearchedArtifact {
    return SearchedArtifactFromJSONTyped(json, false);
}

export function SearchedArtifactFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchedArtifact {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'createdOn': json['createdOn'],
        'createdBy': json['createdBy'],
        'type': ArtifactTypeFromJSON(json['type']),
        'labels': !exists(json, 'labels') ? undefined : json['labels'],
        'state': ArtifactStateFromJSON(json['state']),
        'modifiedOn': !exists(json, 'modifiedOn') ? undefined : json['modifiedOn'],
        'modifiedBy': !exists(json, 'modifiedBy') ? undefined : json['modifiedBy'],
        'groupId': !exists(json, 'groupId') ? undefined : json['groupId'],
    };
}

export function SearchedArtifactToJSON(value?: SearchedArtifact | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'createdOn': value.createdOn,
        'createdBy': value.createdBy,
        'type': ArtifactTypeToJSON(value.type),
        'labels': value.labels,
        'state': ArtifactStateToJSON(value.state),
        'modifiedOn': value.modifiedOn,
        'modifiedBy': value.modifiedBy,
        'groupId': value.groupId,
    };
}

