/* tslint:disable */
/* eslint-disable */
/**
 * Apicurio Registry API [v2]
 * Apicurio Registry is a datastore for standard event schemas and API designs. Apicurio Registry enables developers to manage and share the structure of their data using a REST interface. For example, client applications can dynamically push or pull the latest updates to or from the registry without needing to redeploy. Apicurio Registry also enables developers to create rules that govern how registry content can evolve over time. For example, this includes rules for content validation and version compatibility.  The Apicurio Registry REST API enables client applications to manage the artifacts in the registry. This API provides create, read, update, and delete operations for schema and API artifacts, rules, versions, and metadata.   The supported artifact types include: - Apache Avro schema - AsyncAPI specification - Google protocol buffers - GraphQL schema - JSON Schema - Kafka Connect schema - OpenAPI specification - Web Services Description Language - XML Schema Definition   **Important**: The Apicurio Registry REST API is available from `https://MY-REGISTRY-URL/apis/registry/v2` by default. Therefore you must prefix all API operation paths with `../apis/registry/v2` in this case. For example: `../apis/registry/v2/ids/globalIds/{globalId}`. 
 *
 * The version of the OpenAPI document: 2.2.0.Final
 * Contact: apicurio@lists.jboss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ArtifactState,
    ArtifactStateFromJSON,
    ArtifactStateFromJSONTyped,
    ArtifactStateToJSON,
} from './ArtifactState';
import {
    ArtifactType,
    ArtifactTypeFromJSON,
    ArtifactTypeFromJSONTyped,
    ArtifactTypeToJSON,
} from './ArtifactType';

/**
 * 
 * @export
 * @interface VersionMetaData
 */
export interface VersionMetaData {
    /**
     * 
     * @type {string}
     * @memberof VersionMetaData
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof VersionMetaData
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof VersionMetaData
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof VersionMetaData
     */
    createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof VersionMetaData
     */
    createdOn: Date;
    /**
     * 
     * @type {ArtifactType}
     * @memberof VersionMetaData
     */
    type: ArtifactType;
    /**
     * 
     * @type {number}
     * @memberof VersionMetaData
     */
    globalId: number;
    /**
     * 
     * @type {ArtifactState}
     * @memberof VersionMetaData
     */
    state?: ArtifactState;
    /**
     * The ID of a single artifact.
     * @type {string}
     * @memberof VersionMetaData
     */
    id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof VersionMetaData
     */
    labels?: Array<string>;
    /**
     * User-defined name-value pairs. Name and value must be strings.
     * @type {{ [key: string]: string; }}
     * @memberof VersionMetaData
     */
    properties?: { [key: string]: string; };
    /**
     * An ID of a single artifact group.
     * @type {string}
     * @memberof VersionMetaData
     */
    groupId?: string;
    /**
     * 
     * @type {number}
     * @memberof VersionMetaData
     */
    contentId: number;
}

export function VersionMetaDataFromJSON(json: any): VersionMetaData {
    return VersionMetaDataFromJSONTyped(json, false);
}

export function VersionMetaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionMetaData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': json['version'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'createdBy': json['createdBy'],
        'createdOn': (new Date(json['createdOn'])),
        'type': ArtifactTypeFromJSON(json['type']),
        'globalId': json['globalId'],
        'state': !exists(json, 'state') ? undefined : ArtifactStateFromJSON(json['state']),
        'id': json['id'],
        'labels': !exists(json, 'labels') ? undefined : json['labels'],
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
        'groupId': !exists(json, 'groupId') ? undefined : json['groupId'],
        'contentId': json['contentId'],
    };
}

export function VersionMetaDataToJSON(value?: VersionMetaData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'name': value.name,
        'description': value.description,
        'createdBy': value.createdBy,
        'createdOn': (value.createdOn.toISOString()),
        'type': ArtifactTypeToJSON(value.type),
        'globalId': value.globalId,
        'state': ArtifactStateToJSON(value.state),
        'id': value.id,
        'labels': value.labels,
        'properties': value.properties,
        'groupId': value.groupId,
        'contentId': value.contentId,
    };
}

